api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "npipe:////.//pipe//docker_engine"  # Windows-specific Docker socket path
    exposedByDefault: false
  file:
    filename: /config/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: jaradd@gmail.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
