services:
  couchdb:
    image: couchdb
    container_name: CouchDB
    hostname: couchdb
    mem_limit: 2g
    network_mode: host
    volumes:
      - .:/opt/couchdb/data:rw
    environment:
     COUCHDB_USER: delorenj
     COUCHDB_PASSWORD: admin123
    restart: always
